import type { Trade } from "../components/TradeCard";
import { createConfluenceFactor } from "../types/confluence";
import { generateMockCandles } from "../components/CandlestickChart";

// Helper to generate mock trades with new confluence system
export function generateMockTrades(): Trade[] {
  return [
    // KCU Strategy: EMA(8) Bounce
    {
      id: "1",
      symbol: "SPY",
      setup: "EMA(8) Bounce + PC",
      price: 452.40,
      change: 2.45,
      changePercent: 0.54,
      conviction: "HIGH",
      entry: 451.50,
      target: 458.00,
      stop: 449.00,
      riskReward: "2.6:1",
      status: "SETUP_READY",
      confluenceFactors: [
        createConfluenceFactor("8-EMA", "Aligned", "HIGH", true, "Price respecting 8-EMA on trend"),
        createConfluenceFactor("VWAP", "Above", "HIGH", true, "Trading above VWAP - bullish"),
        createConfluenceFactor("Hourly Level", "$451.50", "MEDIUM", true, "Strong support zone"),
        createConfluenceFactor("Fibonacci", "0.236", "MEDIUM", true, "Retracement to key Fib level"),
        createConfluenceFactor("Patient Candle", "Contained", "HIGH", true, "PC fully inside prior range"),
        createConfluenceFactor("Volume", "Increasing", "MEDIUM", true),
      ],
      timeframe: "5m",
      dayType: "TREND",
      patientCandle: {
        isContained: true,
        pcHigh: 451.80,
        pcLow: 451.20,
        pcOpen: 451.70,
        pcClose: 451.35,
        priorHigh: 452.50,
        priorLow: 450.80,
        priorOpen: 451.20,
        priorClose: 452.10,
        direction: "LONG",
      },
      priceData: generateMockCandles(451.50, 30, 0.015, "up"),
      marketPhase: "POST_10",
      tradeState: "SETUP",
      alertHistory: [],
    },
    
    // KCU Strategy: King & Queen
    {
      id: "2",
      symbol: "QQQ",
      setup: "King & Queen",
      price: 388.75,
      change: -1.25,
      changePercent: -0.32,
      conviction: "HIGH",
      entry: 387.00,
      target: 395.00,
      stop: 385.00,
      riskReward: "4:1",
      status: "ACTIVE",
      confluenceFactors: [
        createConfluenceFactor("ORB Line", "Breakout", "HIGH", true, "Clean break above opening range"),
        createConfluenceFactor("VWAP", "Reclaim", "HIGH", true, "VWAP reclaimed with volume"),
        createConfluenceFactor("8-EMA", "Aligned", "HIGH", true, "8-EMA providing support"),
        createConfluenceFactor("21-EMA", "Sloping Up", "MEDIUM", true, "Trend confirmed on 21-EMA"),
        createConfluenceFactor("Hourly Level", "$387", "HIGH", true, "Major support confluence"),
        createConfluenceFactor("Patient Candle", "Contained", "HIGH", true),
      ],
      timeframe: "2m",
      dayType: "TREND",
      patientCandle: {
        isContained: true,
        pcHigh: 387.30,
        pcLow: 386.90,
        pcOpen: 387.20,
        pcClose: 387.05,
        priorHigh: 388.00,
        priorLow: 386.50,
        priorOpen: 387.50,
        priorClose: 386.80,
        direction: "LONG",
      },
      priceData: generateMockCandles(387.00, 30, 0.012, "up"),
      marketPhase: "POST_10",
      tradeState: "SETUP",
      alertHistory: [],
    },
    
    // Universal Strategy: Breakout Retest
    {
      id: "3",
      symbol: "IWM",
      setup: "Breakout Retest",
      price: 215.20,
      change: 1.50,
      changePercent: 0.70,
      conviction: "MEDIUM",
      entry: 214.00,
      target: 220.00,
      stop: 212.50,
      riskReward: "4:1",
      status: "SETUP_READY",
      confluenceFactors: [
        createConfluenceFactor("Structural Level", "$214", "HIGH", true, "Key resistance flipped to support"),
        createConfluenceFactor("Volume Surge", "2.3x", "HIGH", true, "Volume 2.3x average on breakout"),
        createConfluenceFactor("RVOL", "1.8x", "MEDIUM", true, "Elevated relative volume"),
        createConfluenceFactor("EM Slope", "Bullish", "MEDIUM", true, "Moving averages sloping up"),
        createConfluenceFactor("ATR", "Expanding", "LOW", true, "Volatility increasing"),
      ],
      timeframe: "15m",
      dayType: "TREND",
      priceData: generateMockCandles(214.00, 30, 0.018, "up"),
      marketPhase: "POST_10",
      tradeState: "SETUP",
      alertHistory: [],
    },
    
    // Universal Strategy: Power Hour
    {
      id: "4",
      symbol: "DIA",
      setup: "Power Hour",
      price: 378.90,
      change: 0.20,
      changePercent: 0.05,
      conviction: "MEDIUM",
      entry: 377.50,
      target: 383.00,
      stop: 376.00,
      riskReward: "3.7:1",
      status: "SETUP_FORMING",
      confluenceFactors: [
        createConfluenceFactor("VWAP", "Reclaim", "HIGH", true, "VWAP reclaimed in power hour"),
        createConfluenceFactor("Trend Inflection", "Bullish", "MEDIUM", true, "Shift from bear to bull"),
        createConfluenceFactor("Volume", "Increasing", "HIGH", true, "Power hour volume surge"),
        createConfluenceFactor("Time", "14:45 ET", "LOW", true, "Final hour window"),
      ],
      timeframe: "5m",
      dayType: "TREND",
      priceData: generateMockCandles(377.50, 30, 0.013, "up"),
      marketPhase: "CLOSE",
      tradeState: "SETUP",
      alertHistory: [],
    },
    
    // Options Strategy: IV Expansion Breakout
    {
      id: "5",
      symbol: "AAPL",
      setup: "IV Expansion Breakout",
      price: 182.30,
      change: 1.80,
      changePercent: 1.00,
      conviction: "HIGH",
      entry: 181.00,
      target: 188.00,
      stop: 179.00,
      riskReward: "3.5:1",
      status: "ACTIVE",
      confluenceFactors: [
        createConfluenceFactor("Price Breakout", "Confirmed", "HIGH", true, "Clean break of resistance"),
        createConfluenceFactor("IVP Spike", "+18%", "HIGH", true, "IV percentile jumped 18%"),
        createConfluenceFactor("IV > EM", "Expanding", "MEDIUM", true, "IV rising above moving average"),
        createConfluenceFactor("Call Flow", "Bullish", "MEDIUM", true, "Unusual call activity detected"),
        createConfluenceFactor("Volume", "2.1x", "HIGH", true),
      ],
      timeframe: "15m",
      dayType: "TREND",
      priceData: generateMockCandles(181.00, 30, 0.02, "up"),
      marketPhase: "POST_10",
      event: "EARNINGS",
      tradeState: "SETUP",
      alertHistory: [],
    },
    
    // Invalid Setup Example
    {
      id: "6",
      symbol: "TSLA",
      setup: "VWAP Strategy",
      price: 242.15,
      change: -2.35,
      changePercent: -0.96,
      conviction: "LOW",
      entry: 240.00,
      target: 250.00,
      stop: 237.00,
      riskReward: "3.3:1",
      status: "DISMISSED",
      confluenceFactors: [
        createConfluenceFactor("VWAP", "Below", "LOW", true, "Below VWAP - weak"),
        createConfluenceFactor("200 SMA", "Headwind", "HIGH", true, "200 SMA blocking upside"),
        createConfluenceFactor("Patient Candle", "Invalid", "LOW", false, "PC breach detected"),
        createConfluenceFactor("Volume", "Below Avg", "LOW", false),
        createConfluenceFactor("Trend", "Weak", "LOW", false),
      ],
      timeframe: "5m",
      dayType: "CHOP",
      patientCandle: {
        isContained: false,
        pcHigh: 241.80,
        pcLow: 240.20,
        pcOpen: 241.50,
        pcClose: 240.60,
        priorHigh: 241.50,
        priorLow: 239.80,
        priorOpen: 240.50,
        priorClose: 241.20,
        direction: "LONG",
      },
      priceData: generateMockCandles(240.00, 30, 0.02, "down"),
      warnings: {
        sma200Headwind: true,
        pcInvalid: true,
      },
      marketPhase: "POST_10",
      tradeState: "SETUP",
      alertHistory: [],
    },
    
    // Universal Strategy: Momentum
    {
      id: "7",
      symbol: "NVDA",
      setup: "Bullish Flag Breakout",
      price: 485.60,
      change: 8.20,
      changePercent: 1.72,
      conviction: "HIGH",
      entry: 483.00,
      target: 495.00,
      stop: 480.00,
      riskReward: "4:1",
      status: "ACTIVE",
      confluenceFactors: [
        createConfluenceFactor("Pattern", "Bull Flag", "HIGH", true, "Textbook consolidation after rally"),
        createConfluenceFactor("Volume", "Breakout", "HIGH", true, "Volume confirming breakout"),
        createConfluenceFactor("Trend", "Strong", "HIGH", true, "Higher highs & higher lows"),
        createConfluenceFactor("RVOL", "3.2x", "HIGH", true, "3.2x relative volume"),
        createConfluenceFactor("Momentum", "Accelerating", "MEDIUM", true),
      ],
      timeframe: "15m",
      dayType: "TREND",
      priceData: generateMockCandles(483.00, 30, 0.025, "up"),
      marketPhase: "POST_10",
      tradeState: "SETUP",
      alertHistory: [],
    },
    
    // Monitoring State Example
    {
      id: "8",
      symbol: "AMD",
      setup: "Support/Resistance Bounce",
      price: 142.80,
      change: 0.45,
      changePercent: 0.32,
      status: "MONITORING",
      confluenceFactors: [
        createConfluenceFactor("S/R Level", "$142.50", "MEDIUM", true, "Approaching support"),
        createConfluenceFactor("Volume", "Average", "LOW", true),
        createConfluenceFactor("Trend", "Forming", "LOW", false, "Waiting for confirmation"),
      ],
      timeframe: "15m",
      dayType: "UNKNOWN",
      priceData: generateMockCandles(142.80, 30, 0.01, "sideways"),
      tradeState: "SETUP",
      alertHistory: [],
    },
  ];
}
