#!/bin/bash

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║           🧹 CLEANUP OLD DOCUMENTATION FILES 🧹               ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

echo "This script will DELETE all the old CSS troubleshooting docs"
echo "that are no longer needed now that we know it's a backend issue."
echo ""
echo "⚠️  WARNING: This will permanently delete files!"
echo ""
read -p "Continue? (y/n) " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo "Cancelled."
    exit 1
fi

echo ""
echo "Deleting old CSS troubleshooting files..."

# List of files to delete (all the CSS-related docs)
OLD_FILES=(
  "ALL-IMPORTS-FIXED.md"
  "CACHE-BUG-FOUND.md"
  "CACHE-IS-THE-PROBLEM.md"
  "CHECK-GITHUB-VS-LOCAL.md"
  "CHECKLIST-TWO-FILES.txt"
  "CHECKLIST.md"
  "CLICK-HERE-TO-FIX-CSS.txt"
  "COMPREHENSIVE-FIX-ALL-IMPORTS.md"
  "COMPREHENSIVE-LOGGING-ADDED.md"
  "COPY-THIS-PACKAGE-JSON.md"
  "COPY-THIS-PACKAGE-JSON.txt"
  "COPY-THIS-VERCEL-JSON.txt"
  "COPY-THIS-VITE-CONFIG-TS.txt"
  "CORRECT-PACKAGE-JSON.json"
  "CRITICAL-CSS-NOT-BUILDING.md"
  "CRITICAL-FIX-APPLIED.md"
  "CRITICAL-MISSING-STEPS.md"
  "DEBUG-QUICK-REFERENCE.md"
  "DELETE-PACKAGE-LOCK-AND-PUSH.sh"
  "DEPLOY-CSS-FIX-TO-VERCEL.sh"
  "DEPLOY-FIX-NOW.sh"
  "DEPLOY-NOW.md"
  "DEPLOY-THIS-NOW.md"
  "DEPLOY-WITH-CORRECT-VITE.md"
  "FINAL-CSS-FIX.sh"
  "FINAL-DEPLOYMENT-INSTRUCTIONS.md"
  "FINAL-FIX-PLUGIN-VERSION.md"
  "FINAL-INSTRUCTIONS.md"
  "FINAL-PUSH.sh"
  "FINAL-SOLUTION.md"
  "FIX-ALL-IMPORTS.sh"
  "FIX-BOTH-FILES-NOW.txt"
  "FIX-ON-GITHUB-WEB-NOW.txt"
  "FIX-POSTINSTALL-ERROR.md"
  "FIX-THREE-FILES-NOW.txt"
  "FIX-VITE-CONFIG-SWC-ERROR.md"
  "FIXES-APPLIED.md"
  "FORCE-PUSH-WITH-TOKEN.sh"
  "GITHUB-DIRECT-FIX.md"
  "GITHUB-EDIT-INSTRUCTIONS.txt"
  "GITHUB-INSTRUCTIONS.md"
  "HOW-TO-DISABLE-VERCEL-CACHE.md"
  "INLINE-POSTCSS-FIX.md"
  "LOGGING-GUIDE.md"
  "NUCLEAR-OPTION-APPLIED.md"
  "NUCLEAR-OPTION-PACKAGE-LOCK.md"
  "PUSH-AND-DEPLOY.sh"
  "PUSH-FROM-GITHUB-WEB.md"
  "PUSH-PACKAGE-JSON-AGAIN.md"
  "PUSH-THESE-THREE-FILES.md"
  "PUSH-TO-GITHUB-NOW.sh"
  "PUSH-WITH-LOGGING.txt"
  "README-FIX-CSS-NOW.md"
  "REPLACE-YOUR-PACKAGE-JSON-NOW.md"
  "ROOT-CAUSE-FOUND.md"
  "RUN-THESE-COMMANDS-NOW.md"
  "RUN-THIS-NOW.txt"
  "RUN-THIS-TO-FIX-CSS.md"
  "SIMPLE-TWO-FILE-FIX.txt"
  "SIMPLEST-FIX-REMOVE-VERIFICATION.md"
  "SOLUTION-VITE-6-PROBLEM.md"
  "START-HERE-GITHUB-WEB.txt"
  "START-HERE.txt"
  "SUPER-SIMPLE-FIX.sh"
  "ULTRA-SIMPLE-STEPS.txt"
  "URGENT-FIX-APPLIED.md"
  "URGENT-YOU-MUST-RUN-NPM-INSTALL-LOCALLY.md"
  "VERCEL-WRONG-COMMIT.md"
  "VERIFY-FIX.sh"
  "WHAT-TO-LOOK-FOR.md"
  "WHY-IT-FAILED-EXPLAINED.txt"
  "YOU-FORGOT-PACKAGE-JSON.md"
  "check-github-commit.sh"
  "deploy-fixed.sh"
  "fix-and-deploy-css.sh"
  "fix-local-versioned-imports.sh"
  "test-build.bat"
  "test-build.sh"
  "test-tailwind-build.sh"
  "verify-before-push.sh"
  "verify-css-build.js"
  "verify-imports-fixed.sh"
  "verify-vite-version.js"
  "vite.config.build-logger.ts"
)

DELETED=0
NOT_FOUND=0

for file in "${OLD_FILES[@]}"; do
  if [ -f "$file" ]; then
    rm "$file"
    echo "  ✓ Deleted: $file"
    ((DELETED++))
  else
    echo "  - Not found: $file"
    ((NOT_FOUND++))
  fi
done

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  ✅ Deleted $DELETED files"
echo "  ℹ️  $NOT_FOUND files already removed"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "🎯 IMPORTANT FILES TO KEEP:"
echo ""
echo "  Backend Connection (NEW):"
echo "    - START-HERE-BACKEND-ISSUE.md"
echo "    - FIX-BACKEND-CONNECTION-NOW.md"
echo "    - BACKEND-FIX-SIMPLE.txt"
echo "    - BACKEND-CONNECTION-TEST.md"
echo "    - VISUAL-GUIDE.txt"
echo ""
echo "  Deployment:"
echo "    - DEPLOY-TO-NETLIFY.md"
echo "    - NETLIFY-QUICKSTART.txt"
echo "    - NETLIFY-READY-CHECKLIST.txt"
echo "    - WHY-NETLIFY-IS-BETTER.md"
echo "    - netlify.toml"
echo ""
echo "  Original Docs:"
echo "    - README.md"
echo "    - STATUS.md"
echo "    - DEPLOY.md"
echo "    - docs/ directory"
echo ""
echo "Done! 🎉"
